
export const HACKATHONS = [
  {
    id: 1,
    emoji: '🤖',
    bg: 'linear-gradient(135deg,#ede9fe,#ddd6fe)',
    tag: 'AI/ML',
    tagBg: '#ede9fe',
    tagColor: '#4f46e5',
    title: 'Google AI Hackathon 2025',
    org: 'Google Developer Groups',
    deadline: 'Jun 15, 2025',
    mode: 'Online',
    prize: '₹10,00,000',
    team: '1–4 members',
    friends: [
      { i: 'AS', c: '#ec4899' },
      { i: 'RK', c: '#f59e0b' },
      { i: 'NP', c: '#10b981' },
    ],
    friendText: 'Aarav, Riya +1 are interested',
    collab: 92,
    tags: ['#AI', '#ML', '#Python'],
    category: 'upcoming',
  },
  {
    id: 2,
    emoji: '🌐',
    bg: 'linear-gradient(135deg,#d1fae5,#a7f3d0)',
    tag: 'Web3',
    tagBg: '#d1fae5',
    tagColor: '#059669',
    title: 'ETHIndia Hackathon',
    org: 'Devfolio × Ethereum Foundation',
    deadline: 'Jul 3, 2025',
    mode: 'Hybrid · Bangalore',
    prize: '₹25,00,000',
    team: '2–5 members',
    friends: [
      { i: 'AS', c: '#ec4899' },
      { i: 'VK', c: '#4f46e5' },
    ],
    friendText: 'Aarav & Vikram are going',
    collab: 78,
    tags: ['#Web3', '#Solidity', '#DeFi'],
    category: 'open',
  },
  {
    id: 3,
    emoji: '🎮',
    bg: 'linear-gradient(135deg,#fce7f3,#fbcfe8)',
    tag: 'Gaming',
    tagBg: '#fce7f3',
    tagColor: '#be185d',
    title: 'GameJam India — 48hr Sprint',
    org: 'IndieGame Society',
    deadline: 'May 25, 2025',
    mode: 'Online',
    prize: '₹2,00,000',
    team: 'Solo or 2',
    friends: [{ i: 'NP', c: '#10b981' }],
    friendText: 'Neha is participating',
    collab: 65,
    tags: ['#Unity', '#Godot', '#GameDev'],
    category: 'open',
  },
  {
    id: 4,
    emoji: '💊',
    bg: 'linear-gradient(135deg,#fef3c7,#fde68a)',
    tag: 'HealthTech',
    tagBg: '#fef3c7',
    tagColor: '#b45309',
    title: 'HackHealth — Medical AI Challenge',
    org: 'AIIMS × Microsoft',
    deadline: 'Aug 10, 2025',
    mode: 'In-Person · Delhi',
    prize: '₹5,00,000',
    team: '2–4 members',
    friends: [
      { i: 'RK', c: '#f59e0b' },
      { i: 'SM', c: '#6366f1' },
    ],
    friendText: 'Riya & Sahil are interested',
    collab: 55,
    tags: ['#HealthAI', '#MedTech', '#OpenCV'],
    category: 'upcoming',
  },
  {
    id: 5,
    emoji: '🌱',
    bg: 'linear-gradient(135deg,#d1fae5,#bbf7d0)',
    tag: 'ClimaTech',
    tagBg: '#d1fae5',
    tagColor: '#059669',
    title: 'Climate Hack 2025',
    org: 'UN Environment × Startup India',
    deadline: 'Sep 1, 2025',
    mode: 'Hybrid · Mumbai',
    prize: '₹8,00,000',
    team: '3–6 members',
    friends: [],
    friendText: '',
    collab: 40,
    tags: ['#ClimaTech', '#Sustainability', '#GreenAI'],
    category: 'upcoming',
  },
]

export const FRIENDS_DATA = [
  { name: 'Aarav Sharma',  handle: '@aarav_s',  initials: 'AS', color: '#ec4899', hacks: 12, mutual: 3, match: 92 },
  { name: 'Riya Kapoor',   handle: '@riya_k',   initials: 'RK', color: '#f59e0b', hacks: 8,  mutual: 5, match: 78 },
  { name: 'Neha Patel',    handle: '@neha_p',   initials: 'NP', color: '#10b981', hacks: 15, mutual: 2, match: 65 },
  { name: 'Vikram Kumar',  handle: '@vikram_k', initials: 'VK', color: '#4f46e5', hacks: 6,  mutual: 7, match: 88 },
  { name: 'Sahil Mehta',   handle: '@sahil_m',  initials: 'SM', color: '#6366f1', hacks: 20, mutual: 1, match: 72 },
]

export const MESSAGES = [
  { name: 'Aarav Sharma', initials: 'AS', color: '#ec4899', preview: 'Are you joining ETHIndia? 👀',        time: '2m', unread: true  },
  { name: 'Riya Kapoor',  initials: 'RK', color: '#f59e0b', preview: 'I saw the Google AI hack, collab?', time: '1h', unread: true  },
  { name: 'Neha Patel',   initials: 'NP', color: '#10b981', preview: "GameJam is OPEN!! Let's go 🎮",     time: '3h', unread: false },
  { name: 'Vikram Kumar', initials: 'VK', color: '#4f46e5', preview: 'Sent you a team invite',            time: '1d', unread: false },
]

export const TAGS = [
  '#AI', '#Web3', '#GameDev', '#MedTech', '#ClimaTech',
  '#Python', '#React', '#OpenSource', '#Blockchain', '#ML', '#100DaysOfCode',
]
